version: "1"
services:
  web:
    build:
      context: . # Path to the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - AWS_ACCESS_KEY_ID=your-access-key
      - AWS_SECRET_ACCESS_KEY=your-secret-key
      - AWS_REGION=your-region
    volumes:
      - .:/app # Mount the current directory to /app in the container
